before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: HDjQrOraoxUCYRD8OkIZAw4B7k4RxvNtDq6+/KFFCOekp6mye4ssKJ+ZcHi/6hiKCJQFrbOI1N1LSwaUEz/IJGmJzd4eedvYoa+kX20WmaZ8QSou272+7/RAKFVWG95eG+7XTi7eDcJVWxNXOBMLyBD7JieSblWFhgGZEepXsiX0LSP8J3RJ3Z9nw1ao5GBz7OIx3ZmUtq4T6oe/XrS/b5JVvWYQuOfzPURnhWV1fS974Kb/WBmp7lDULjdp0w1YpwyOTO+QmF5yIx6fFBW/LrOfwAcy5rWmeJtTP/Jmc6Hc1h9OMN20kfy52KExIlbJeYn/qGC6hv1dl/SUPtKigJ54hX3imZ7RZwBE2Xp3QFpT2iTkca/jVbxoCgd/tzOYWB1wT+6ZLkXeCOVDMkzQ/5PUKo/3VG0GZPvUHvFvrqoCoD0bs1Cab1plljJ/OroHWPL859z6ids1tfNniX8WwDiqF1UMEauZx2lkCtmEYkiQY1Z+Tbh+ucQ29Hg2NYc/8Ud59z3+XCYxDER4ny2TArUMscWcB+PkJm7q52iAfyc/rbEYqc6NDaqC+hqB0zDcaJFT2fLGi6qCCOyEz+UIZJzDTRyhe6Z+p+nVIwJ3REbxJGAAgI3CHEIPInC0cmOQQAPFfjsOPaRA6Z2sUuzoZq8xsJIRxbgCQd6t0/EC43g= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
